import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../state/AuthContext';
import logo from '../../Logo.png';

function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [form, setForm] = useState({ email: '', password: '' });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const handleChange = (e) => {
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await login(form.email, form.password);
      navigate('/');
    } catch (err) {
      setError(err.userMessage || err.response?.data?.message || err.message || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center px-4 relative overflow-hidden bg-slate-950">
      <div className="pointer-events-none absolute inset-0 -z-0">
        <div className="absolute -left-20 top-8 h-72 w-72 rounded-full bg-sky-500/20 blur-3xl" />
        <div className="absolute -right-16 bottom-6 h-72 w-72 rounded-full bg-emerald-500/15 blur-3xl" />
      </div>
      <div className="w-full max-w-md bg-slate-900/78 border border-slate-700/60 rounded-3xl p-8 shadow-xl backdrop-blur">
        <div className="flex items-center gap-2 mb-6">
          <img src={logo} alt="CRM Pro logo" className="h-9 w-9 rounded-xl object-cover ring-2 ring-sky-400/40" />
          <div>
            <h1 className="text-xl font-semibold tracking-tight text-slate-50">Sign in to CRM Pro</h1>
            <p className="text-xs text-slate-400">
              Use the email and temporary password generated by admin while creating your profile.
            </p>
          </div>
        </div>
        {error && (
          <div className="mb-4 text-xs text-red-400 bg-red-950/40 border border-red-900 rounded-lg px-3 py-2">
            {error}
          </div>
        )}
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-xs text-slate-300 mb-1">Email</label>
            <input
              type="email"
              name="email"
              value={form.email}
              onChange={handleChange}
              className="w-full rounded-xl bg-slate-950/80 border border-slate-700 px-3 py-2 text-sm text-slate-100 focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>
          <div>
            <label className="block text-xs text-slate-300 mb-1">Password</label>
            <input
              type="password"
              name="password"
              value={form.password}
              onChange={handleChange}
              className="w-full rounded-xl bg-slate-950/80 border border-slate-700 px-3 py-2 text-sm text-slate-100 focus:outline-none focus:ring-2 focus:ring-sky-500"
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full mt-2 rounded-xl bg-sky-600 hover:bg-sky-500 text-sm font-semibold text-white py-2.5 disabled:opacity-60 disabled:cursor-not-allowed transition-colors"
          >
            {loading ? 'Signing in...' : 'Sign in'}
          </button>
          <div className="text-[11px] text-slate-400 mt-2 space-y-1">
            <p>Admin creates employee, lead, or customer profile from Employees page.</p>
            <p>System auto-generates login using profile email + temporary password.</p>
          </div>
        </form>
      </div>
    </div>
  );
}

export default Login;

